changes | l10n/i18n:
  - "Wholist/Resources/Localization/**/*"

changes | ci:
  - ".github/workflows/**/*"

changes | source:
  - "**/*.cs"
  - "**/*.csproj"
  - "**/packages.lock.json"

changes | docs:
  - "**/*.md"
  - "**/*.txt"
