name: "PR: Plugin Code Changes"

on:
  pull_request:
    branches: [main]
    paths:
      - "Wholist/**.cs"
      - "Wholist/**.csproj"
    types: [ready_for_review, opened, synchronize]

jobs:
  Build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
        DALAMUD_HOME: /tmp/dalamud
        IsCI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Dependencies
        working-directory: Wholist
        run: dotnet restore

      - name: Build Plugin (Dev)
        working-directory: Wholist
        run: dotnet build -c Debug

      - name: Build Plugin (Release)
        working-directory: Wholist
        run: dotnet build -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: Wholist/bin/
